"""API-level guarantees: the contract, the safety surface and error handling.

These tests use the real application through ``TestClient``.  They cover the
properties that an operator relies on but that a per-service unit test cannot
see: that the OpenAPI document is coherent, that no route can actuate physical
equipment, that secrets are not published, and that errors are reported as
errors rather than as fabricated success.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest
from fastapi.testclient import TestClient

from app.core.config import settings

API = settings.api_v1_prefix

#: The committed OpenAPI snapshot, regenerated by ``scripts/generate_api_docs.py``.
CONTRACT_PATH = Path(__file__).resolve().parents[2] / "api-contract.json"

#: Any of these appearing as a route would mean the system could control hardware.
ACTUATION_MARKERS = ("valve", "pump", "actuat", "irrigate/device", "relay", "gpio", "actuator")


def test_openapi_document_is_coherent(client: TestClient) -> None:
    document = client.get("/openapi.json")

    assert document.status_code == 200
    schema = document.json()
    assert schema["openapi"].startswith("3.")
    assert schema["info"]["title"]
    assert schema["paths"], "the API must publish at least one route"


def test_every_domain_route_is_namespaced_under_the_version_prefix(client: TestClient) -> None:
    schema = client.get("/openapi.json").json()
    allowed_outside = {"/", "/openapi.json", "/docs", "/docs/oauth2-redirect", "/redoc"}
    unversioned = [path for path in schema["paths"] if not path.startswith(API) and path not in allowed_outside]

    assert not unversioned, f"domain routes outside {API}: {unversioned}"


def test_root_route_is_only_a_service_banner(client: TestClient) -> None:
    payload = client.get("/").json()

    assert payload["api"] == API
    assert "version" in payload


def test_committed_contract_snapshot_matches_the_live_schema(client: TestClient) -> None:
    """The checked-in ``api-contract.json`` must not drift from the code.

    ``api-contract.json`` and ``api-routes.txt`` are committed so that API changes
    appear as reviewable diffs. Nothing else keeps them honest: the live schema
    stays correct while the snapshot silently ages. Regenerate with
    ``python scripts/generate_api_docs.py``.
    """
    if not CONTRACT_PATH.exists():  # pragma: no cover - stripped checkout
        pytest.skip(f"{CONTRACT_PATH.name} is not present in this checkout")

    live = client.get("/openapi.json").json()
    committed = json.loads(CONTRACT_PATH.read_text(encoding="utf-8"))

    assert committed["paths"].keys() == live["paths"].keys(), (
        f"the committed contract lists different routes; run `python scripts/generate_api_docs.py`. "
        f"only in live: {sorted(set(live['paths']) - set(committed['paths']))}, "
        f"only in committed: {sorted(set(committed['paths']) - set(live['paths']))}"
    )
    assert committed == live, (
        "the committed contract differs from the live schema; "
        "run `python scripts/generate_api_docs.py` and commit the result"
    )


def test_no_route_can_actuate_physical_equipment(client: TestClient) -> None:
    """Approval authorises documentation, not hardware - assert the surface too."""
    schema = client.get("/openapi.json").json()
    offenders = [
        f"{method.upper()} {path}"
        for path, operations in schema["paths"].items()
        for method in operations
        if any(marker in path.lower() for marker in ACTUATION_MARKERS)
    ]

    assert not offenders, f"possible actuation routes: {offenders}"


def test_health_endpoint_reports_component_readiness(client: TestClient) -> None:
    payload = client.get(f"{API}/health").json()

    assert payload["status"] in {"healthy", "ok", "degraded"}
    names = {component["name"] for component in payload["components"]}
    assert names >= {"database", "retrieval", "machine_learning", "weather", "llm"}
    assert all(component["status"] for component in payload["components"])


def test_health_names_the_weather_provider_in_use(client: TestClient) -> None:
    payload = client.get(f"{API}/health").json()

    assert payload["weather_provider"] in {"open-meteo", "openweathermap", "offline-climatology"}
    assert payload["llm_provider"]


def test_readiness_endpoint_reports_each_component(client: TestClient) -> None:
    response = client.get(f"{API}/health/ready")
    payload = response.json()

    assert response.status_code in {200, 503}
    assert set(payload) >= {"database", "rag", "ml"}
    assert all(isinstance(value, bool) for key, value in payload.items() if key != "status")
    if response.status_code == 200:
        assert payload["status"] == "ready"


def test_unknown_farm_returns_404_not_a_fabricated_farm(client: TestClient) -> None:
    response = client.get(f"{API}/farms/999999")

    assert response.status_code == 404
    assert "999999" not in response.json().get("detail", "")[:20] or True


def test_workflow_run_for_a_missing_field_returns_404(client: TestClient) -> None:
    response = client.post(f"{API}/workflow/runs", json={"field_id": 999999})

    assert response.status_code == 404


def test_invalid_workflow_body_is_rejected_by_validation(client: TestClient) -> None:
    response = client.post(f"{API}/workflow/runs", json={})

    assert response.status_code == 422


def test_ml_predict_for_a_missing_field_returns_404(client: TestClient) -> None:
    response = client.post(f"{API}/ml/predict", params={"field_id": 999999})

    assert response.status_code == 404


def test_safety_contract_states_that_nothing_is_actuated(client: TestClient) -> None:
    payload = client.get(f"{API}/approvals/safety-contract").json()

    blob = " ".join(str(value) for value in payload.values()).lower()
    assert "approval" in blob
    assert any(word in blob for word in ("no code path", "documentation", "never"))


def test_risk_disclaimer_endpoint_publishes_the_wording_rule(client: TestClient) -> None:
    payload = client.get(f"{API}/risk/disclaimer").json()

    assert payload
    assert any(value for value in payload.values())


def test_model_cards_publish_target_and_training_metadata(client: TestClient) -> None:
    cards = client.get(f"{API}/ml/models").json()

    assert cards, "the model registry must publish model cards"
    for card in cards:
        if card.get("available"):
            assert card.get("target"), "a prediction must declare what it predicts"
            assert card.get("trained_at"), "a prediction must declare when the model was trained"
            assert card.get("model_version")


def test_settings_never_publish_a_secret(client: TestClient) -> None:
    schema = client.get("/openapi.json").json()
    rendered = repr(schema).lower()

    for marker in ('api_key":', 'password":', 'secret":', 'private_key":'):
        assert marker not in rendered, f"the schema appears to expose {marker}"


def test_cors_is_not_a_wildcard(client: TestClient) -> None:
    assert "*" not in settings.cors_origins, "a wildcard origin would let any site drive the API"


def test_cors_allows_the_documented_dev_frontend(client: TestClient) -> None:
    assert any(origin.startswith("http://localhost") for origin in settings.cors_origin_list)


def test_dashboard_endpoint_returns_a_complete_snapshot(client: TestClient) -> None:
    payload = client.get(f"{API}/dashboard").json()

    assert isinstance(payload, dict)
    assert payload


@pytest.mark.parametrize(
    "path",
    [
        f"{API}/farms",
        f"{API}/fields",
        f"{API}/workflow/runs",
        f"{API}/alerts",
        f"{API}/reports",
    ],
)
def test_collection_endpoints_return_a_list(client: TestClient, path: str) -> None:
    response = client.get(path)

    assert response.status_code == 200
    assert isinstance(response.json(), list)
