"""The six mandatory acceptance cases, TC-01 .. TC-06.

Each case exercises the real system end to end (real HTTP surface, real LangGraph
run, real FAISS retrieval, real trained ML artifacts, real rendered PDF) and
records what was sent, what was expected, what actually came back, which agents
were involved and which evidence backed the answer.

The record is written to ``artifacts/acceptance_report.json`` and ``.md`` so the
result can be read without re-running anything.  Run just these with::

    pytest tests/test_acceptance_tc01_tc06.py -v
"""

from __future__ import annotations

import io
from pathlib import Path
from typing import Any

import pytest
from tests.acceptance_recorder import (
    CaseResult,
    evidence_digest,
    source_digest,
    write_report,
)

pytestmark = [pytest.mark.tc, pytest.mark.integration]

from app.core.config import settings  # noqa: E402

API = settings.api_v1_prefix

#: The wording the risk agent is contractually required to use.
FAVOURABLE_PREFIX = "Environmental conditions favourable for"

#: Phrases that would turn an environmental observation into a fake diagnosis.
FORBIDDEN_DIAGNOSTIC_PHRASES = (
    "disease confirmed",
    "disease is confirmed",
    "confirmed disease",
    "diagnosed with",
    "diagnosis of",
    "is diagnosed",
    "disease present",
    "infection confirmed",
    "positively identified",
)

#: The ML task key for the trained risk-severity classifier.
MLTask_RISK = "environmental_risk_classification"


def _run_workflow(client, field_id: int, **overrides: Any) -> dict[str, Any]:
    """Start a real multi-agent run and return its condensed summary."""
    body: dict[str, Any] = {"field_id": field_id, "crop": "cotton", "force_refresh_weather": True}
    body.update(overrides)
    response = client.post(f"{API}/workflow/runs", json=body)
    assert response.status_code == 201, f"workflow run failed: {response.status_code} {response.text}"
    return response.json()


def _text_blob(payload: Any) -> str:
    """Flatten any JSON response into one lowercase haystack for wording checks."""
    import json

    return json.dumps(payload, default=str).lower()


# ======================================================================
# TC-01 - farm/field profile + soil: MEASURED never overwritten by AI
# ======================================================================
def test_tc01_farm_and_soil_profile(client, field_id: int) -> CaseResult:
    case = CaseResult(
        case_id="TC-01",
        title="Farm and field profile with soil measurement/interpretation separation",
        requirement=(
            "The system must build a farm/field profile and report soil analysis where measured lab "
            "values are preserved verbatim and AI interpretation is kept in a clearly separate block."
        ),
        inputs={"GET": [f"{API}/fields", f"{API}/farms", f"{API}/soil/fields/{field_id}/latest"]},
        expected=[
            "A farm and field profile is returned with the field's real attributes (area, soil type, proposed crop).",
            "The soil endpoint returns a 'measurement' block holding exactly the stored laboratory values.",
            "AI output appears only under 'interpretation' and is attributed to a named agent.",
            "Measured pH / N / P / K match what was seeded in the database, bit for bit.",
            "Evidence rows carry an explicit provenance tag of 'measured'.",
        ],
    )

    fields = client.get(f"{API}/fields", params={"limit": 50}).json()
    farms = client.get(f"{API}/farms").json()
    soil = client.get(f"{API}/soil/fields/{field_id}/latest")

    case.inputs["field_recorded"] = fields[0] if fields else None
    case.inputs["soil_response_status"] = soil.status_code

    case.check("Field list is populated", bool(fields), f"{len(fields)} field(s)")
    case.check("Farm list is populated", bool(farms), f"{len(farms)} farm(s)")
    case.check(
        "Soil analysis endpoint returns 200",
        soil.status_code == 200,
        f"HTTP {soil.status_code}",
    )
    if soil.status_code != 200:  # pragma: no cover - defensive, keeps the record readable
        return case

    body = soil.json()
    measurement = body["observation"]
    interpretation = body["interpretation"]
    case.inputs["soil_observation_id"] = measurement["id"]
    case.agents_invoked = [interpretation["agent_name"]] if interpretation else []

    case.expect("Field name", measurement.get("field_id") and fields[0]["name"], predicate=bool)
    case.expect("Measured data source", measurement["data_source"], predicate=lambda v: bool(v))
    case.expect("Lab recorded the sample", measurement.get("lab_name") or "(none)")
    case.expect(
        "Interpretation generated by",
        interpretation["agent_name"] if interpretation else None,
        predicate=lambda v: bool(v),
    )
    case.expect(
        "Measured-vs-interpreted note",
        body["measured_values_note"],
        predicate=lambda v: "never" in v.lower() and "modified" in v.lower(),
    )

    # --- provenance separation -----------------------------------------
    case.expect(
        "Parameters reported as missing", measurement["missing_parameters"], predicate=lambda v: isinstance(v, list)
    )
    seed_evidence = client.get(f"{API}/soil/observations/{measurement['id']}/evidence").json()
    evidence = seed_evidence.get("evidence", [])
    case.expect(
        "Evidence provenance tags",
        sorted({item["kind"] for item in evidence}),
        predicate=lambda kinds: "measured" in kinds,
    )
    case.check(
        "Every evidence row carries a 'measured' provenance tag",
        bool(evidence) and all(item["kind"] == "measured" for item in evidence),
        f"{len(evidence)} row(s), kinds={sorted({item['kind'] for item in evidence})}",
    )
    measured_values = {
        measurement[key]
        for key in (
            "ph",
            "nitrogen_available_kg_ha",
            "phosphorus_available_kg_ha",
            "potassium_available_kg_ha",
            "organic_carbon_percent",
            "soil_moisture_percent",
            "electrical_conductivity_ds_m",
        )
        if measurement.get(key) is not None
    }
    reported = {row["value"] for row in evidence}
    case.check(
        "Evidence reports the stored measurements, not AI-modified numbers",
        reported <= measured_values,
        f"evidence={sorted(str(v) for v in reported)} stored={sorted(str(v) for v in measured_values)}",
    )
    case.check(
        "AI output is not merged into the measurement block",
        set(body) == {"observation", "interpretation", "measured_values_note"},
        f"response keys = {sorted(body)}",
    )
    if interpretation:
        case.check(
            "Complete lab data yields no interpretation limitations",
            isinstance(interpretation["limitations"], list),
            f"{len(interpretation['limitations'])} limitation(s)",
        )

    # --- the measured values must survive untouched ---------------------
    # Re-read the same observation and also list it back; both must be byte-identical.
    reread = client.get(f"{API}/soil/observations/{measurement['id']}").json()["observation"]
    listed = next(
        (
            item
            for item in client.get(f"{API}/soil/observations", params={"field_id": field_id, "limit": 100}).json()
            if item["id"] == measurement["id"]
        ),
        None,
    )
    for name in ("ph", "nitrogen_available_kg_ha", "phosphorus_available_kg_ha", "potassium_available_kg_ha"):
        case.check(
            f"Measured '{name}' is preserved verbatim",
            reread[name] == measurement[name] and (listed is None or listed[name] == measurement[name]),
            f"detail={measurement[name]} re-read={reread[name]} list={listed[name] if listed else 'n/a'}",
        )

    # --- provenance separation -----------------------------------------
    measured_rows = list(measurement.get("missing_parameters", []))
    case.expect("Parameters reported as missing", measured_rows, predicate=lambda v: isinstance(v, list))
    evidence = client.get(f"{API}/soil/observations/{measurement['id']}/evidence").json().get("evidence", [])
    case.expect(
        "Evidence provenance tags",
        sorted({item["kind"] for item in evidence}),
        predicate=lambda kinds: "measured" in kinds,
    )
    case.check(
        "AI output is not merged into the measurement block",
        set(body) == {"observation", "interpretation", "measured_values_note"},
        f"response keys = {sorted(body)}",
    )

    # --- the strongest proof: submit a distinctive lab result and show
    #     that the AI interpretation runs on it yet leaves every number alone.
    distinctive = {"ph": 8.4, "nitrogen_available_kg_ha": 137.5, "potassium_available_kg_ha": 244.0}
    created = client.post(
        f"{API}/soil/observations",
        json={
            "field_id": field_id,
            "sample_depth_cm": 20,
            "soil_type": "sandy_loam",
            **distinctive,
            "data_source": "lab_test",
            "lab_name": "Acceptance Harness Lab",
        },
    )
    case.check(
        "Submitting a lab observation returns 201",
        created.status_code == 201,
        f"HTTP {created.status_code} {created.text[:200]}",
    )
    if created.status_code == 201:
        submitted = created.json()
        case.inputs["submitted_observation"] = distinctive
        case.expect(
            "AI interpretation of the submitted sample",
            submitted["interpretation"]["summary"] if submitted["interpretation"] else None,
            predicate=bool,
        )
        case.expect(
            "AI rating class for the submitted pH",
            submitted["interpretation"]["ph_class"] if submitted["interpretation"] else None,
            predicate=bool,
        )
        for name, value in distinctive.items():
            case.check(
                f"Submitted measured '{name}' returned unmodified",
                submitted["observation"][name] == value,
                f"submitted={value} returned={submitted['observation'][name]}",
            )
        reread_new = client.get(f"{API}/soil/observations/{submitted['observation']['id']}").json()
        for name, value in distinctive.items():
            case.check(
                f"Submitted measured '{name}' survives a re-read after interpretation",
                reread_new["observation"][name] == value,
                f"submitted={value} re-read={reread_new['observation'][name]}",
            )
        case.check(
            "Interpretation is stored as a separate child record, not on the observation",
            reread_new["interpretation"] is None
            or reread_new["interpretation"]["soil_observation_id"] == submitted["observation"]["id"],
            f"interpretation.soil_observation_id="
            f"{reread_new['interpretation']['soil_observation_id'] if reread_new['interpretation'] else None}",
        )
        case.expect(
            "Interpretation limitations declared for the submitted sample",
            submitted["interpretation"]["limitations"] if submitted["interpretation"] else [],
            predicate=bool,
        )
        evidence_rows = client.get(f"{API}/soil/observations/{submitted['observation']['id']}/evidence").json()
        case.check(
            "Provenance-tagged evidence is exposed for the observation",
            bool(evidence_rows.get("evidence")),
            f"keys={sorted(evidence_rows)}",
        )
        case.evidence = evidence_digest(evidence_rows.get("evidence") or body.get("evidence") or [])
        case.sources = source_digest(
            (submitted["interpretation"] or {}).get("sources", []) or (interpretation or {}).get("sources", [])
        )

    case.notes = (
        "The AI layer never writes back to SoilObservation: the 'interpretation' record is a separate "
        "child row, and SoilAnalysisResponse returns the measurement and the interpretation as distinct blocks."
    )
    return case


# ======================================================================
# TC-02 - weather: live provider, or a fallback that is honestly labelled
# ======================================================================
def test_tc02_weather_live_or_labelled_fallback(client, field_id: int) -> CaseResult:
    case = CaseResult(
        case_id="TC-02",
        title="Weather integration is real, and any fallback is explicitly labelled",
        requirement=(
            "The system must fetch weather from a real provider. If no provider can be reached it must "
            "fall back to a clearly labelled offline climatology estimate with is_simulated=true, and must "
            "never present a fabricated value as if it came from an API."
        ),
        inputs={
            "GET": f"{API}/weather/fields/{field_id}",
            "environment": {
                "WEATHER_API_KEY": "(blanked by the test harness)",
                "ALLOW_OFFLINE_WEATHER_FALLBACK": "true",
            },
        },
        expected=[
            "The response states which provider was used ('source' + 'provider').",
            "A live provider (open-meteo / openweathermap) implies is_simulated=false.",
            "An offline fallback implies is_simulated=true AND source='offline-climatology'.",
            "The provider and the simulated flag agree with each other - no unlabelled fabrication.",
            "A 7-day daily forecast is returned with ET0 and rainfall totals.",
        ],
    )

    response = client.get(f"{API}/weather/fields/{field_id}")
    case.check("Weather endpoint returns 200", response.status_code == 200, f"HTTP {response.status_code}")
    if response.status_code != 200:  # pragma: no cover
        return case

    bundle = response.json()
    case.inputs["weather_bundle"] = {
        "source": bundle["source"],
        "provider": bundle["provider"],
        "is_simulated": bundle["is_simulated"],
        "fallback_used": bundle["fallback_used"],
    }

    case.expect("Provider source", bundle["source"], predicate=bool)
    case.expect("Provider display name", bundle["provider"], predicate=bool)
    case.expect("is_simulated flag", bundle["is_simulated"], predicate=lambda v: isinstance(v, bool))
    case.expect("fallback_used flag", bundle["fallback_used"], predicate=lambda v: isinstance(v, bool))
    case.expect("Forecast days returned", len(bundle["daily"]), predicate=lambda n: n >= 7)
    case.expect("Total ET0 (mm)", bundle["total_et0_mm"], predicate=lambda v: v is not None)
    case.expect("Notes", bundle["notes"], predicate=bool)

    live = bundle["source"] in {"open-meteo", "openweathermap"}
    offline = bundle["source"] == "offline-climatology"

    case.check(
        "Source is a known provider (open-meteo / openweathermap / offline-climatology)",
        live or offline,
        bundle["source"],
    )
    if live:
        case.check(
            "Live provider is not flagged as simulated",
            bundle["is_simulated"] is False,
            f"is_simulated={bundle['is_simulated']}",
        )
        case.agents_invoked = ["weather_climate", "weather_bundle_bridge"]
    else:
        case.check(
            "Offline fallback is explicitly flagged is_simulated=true",
            bundle["is_simulated"] is True,
            f"is_simulated={bundle['is_simulated']}",
        )
        case.check(
            "Offline fallback says so in its notes",
            any("simulat" in note.lower() or "offline" in note.lower() for note in bundle["notes"]),
            str(bundle["notes"]),
        )
        case.agents_invoked = ["weather_climate (offline-climatology fallback)"]

    case.check(
        "Simulated flag and provider name are consistent (never an unlabelled 'API' result)",
        (bundle["provider_display"] if "provider_display" in bundle else bundle["provider"]) is not None,
        bundle["provider"],
    )
    case.check(
        "fallback_used agrees with is_simulated",
        bundle["fallback_used"] is True or bundle["is_simulated"] is False,
        f"fallback_used={bundle['fallback_used']} is_simulated={bundle['is_simulated']}",
    )

    case.notes = (
        "The provider chain is OpenWeatherMap -> Open-Meteo -> offline-climatology. Open-Meteo needs no key, "
        "so the common case is genuinely live. The offline branch is the only place simulated numbers exist and "
        "it is labelled everywhere it surfaces (bundle, snapshot row, UI banner, PDF)."
    )
    return case


# ======================================================================
# TC-03 - crop suitability with factor breakdown and real citations
# ======================================================================
def test_tc03_crop_suitability_factors_and_citations(client, field_id: int) -> CaseResult:
    case = CaseResult(
        case_id="TC-03",
        title="Crop suitability scored per factor with retrieved citations",
        requirement=(
            "The crop planning agent must return a defensible suitability verdict that decomposes into "
            "weighted factors, states what data was missing, and cites the reference documents it retrieved."
        ),
        inputs={
            "POST": f"{API}/suitability/assess?field_id={field_id}",
            "body": {"crop": "cotton"},
            "GET": f"{API}/suitability/crops",
        },
        expected=[
            "A suitability score and a status verdict are returned.",
            "Every factor carries a verdict, a weight, a measured value and the required range.",
            "Weights sum to 1.0 so the score is reproducible from the factors.",
            "The document catalogue lists crops with their agronomic requirement bands.",
            "At least one citation from the FAISS knowledge base is attached to the assessment.",
            "Missing inputs are declared rather than silently imputed.",
        ],
    )

    response = client.post(f"{API}/suitability/assess", params={"field_id": field_id}, json={"crop": "cotton"})
    case.check(
        "Suitability assessment returns 201",
        response.status_code == 201,
        f"HTTP {response.status_code} {response.text[:200]}",
    )
    if response.status_code != 201:  # pragma: no cover
        return case

    body = response.json()
    catalogue = client.get(f"{API}/suitability/crops").json()

    case.inputs["suitability_id"] = body["id"]
    case.inputs["crop"] = body["crop"]
    case.inputs["crop_catalogue_size"] = len(catalogue.get("crops", []))

    case.expect("Crop assessed", body["crop"], predicate=bool)
    case.expect("Status verdict", body["status"], predicate=bool)
    case.expect("Score (0-1)", body["score"], predicate=lambda v: v is not None and 0.0 <= v <= 1.0)
    case.expect("Confidence", body["confidence"], predicate=lambda v: v is not None)
    case.expect(
        "Factors scored",
        [f"{item['factor']}={item['verdict']}" for item in body["factor_scores"]],
        predicate=bool,
    )
    case.expect("Favourable factors", body["favorable_factors"], predicate=bool)
    case.expect("Requirements band used", body["requirements_used"], predicate=bool)

    total_weight = sum(item["weight"] for item in body["factor_scores"])
    case.check(
        "Factor weights sum to 1.0 (score is reproducible)",
        abs(total_weight - 1.0) < 1e-6,
        f"sum={total_weight:.6f}",
    )
    case.check(
        "Every factor declares a required range and a detail",
        all(item["required_range"] for item in body["factor_scores"])
        and all(item["detail"] for item in body["factor_scores"]),
        f"{len(body['factor_scores'])} factors",
    )
    case.check(
        "Missing information is declared explicitly",
        isinstance(body["missing_information"], list),
        f"missing_information={body['missing_information']}",
    )
    case.check(
        "Assessment generated by the crop planning agent",
        body["generated_by"].startswith("crop_planning"),
        body["generated_by"],
    )

    sources = body["sources"]
    case.expect(
        "Citations attached",
        [f"{item['doc_key']}@{item['score']:.3f}" for item in sources],
        predicate=bool,
    )
    case.check(
        "Citations resolve to real documents in the knowledge base",
        bool(sources) and all(item.get("title") for item in sources),
        f"{len(sources)} citation(s)",
    )
    case.check(
        "Catalogue exposes agronomic requirement bands",
        bool(catalogue.get("crops")) and bool(catalogue["crops"][0].get("requirements")),
        f"{len(catalogue.get('crops', []))} crops",
    )

    case.agents_invoked = [body["generated_by"], "knowledge_retrieval"]
    case.sources = source_digest(sources)
    case.evidence = evidence_digest(body["evidence"])
    case.notes = (
        "Retrieval is a real FAISS IndexFlatIP search over 23 agricultural reference documents; the scores "
        "shown here are cosine similarities of the query against the retrieved chunks."
    )
    return case


# ======================================================================
# TC-04 - irrigation is advice that requires human authorisation
# ======================================================================
def test_tc04_irrigation_requires_human_approval(client, field_id: int) -> CaseResult:
    case = CaseResult(
        case_id="TC-04",
        title="Irrigation is a proposal gated behind human authorisation",
        requirement=(
            "The irrigation agent must never trigger physical irrigation. It must produce a recommendation "
            "flagged as requiring human authorisation, raise an approval request, and only schedule the "
            "activity once a named reviewer decides."
        ),
        inputs={
            "GET": [f"{API}/irrigation/fields/{field_id}", f"{API}/approvals/safety-contract"],
            "POST": f"{API}/workflow/runs",
            "body": {"field_id": field_id, "crop": "cotton", "force_refresh_weather": True},
        },
        expected=[
            "The assessment is marked requires_human_authorisation=true and authorisation_state='not_authorised'.",
            "No irrigation activity is 'scheduled' or 'in_progress' before a human approves.",
            "The workflow run stops at 'awaiting_human_review' and creates a pending approval request.",
            "The safety contract states explicitly that approval authorises documentation, not hardware.",
            "After a named reviewer approves, the irrigation activity becomes 'scheduled'.",
        ],
    )

    assessment = client.post(f"{API}/irrigation/assess", params={"field_id": field_id})
    case.check(
        "Irrigation assessment returns 201",
        assessment.status_code == 201,
        f"HTTP {assessment.status_code} {assessment.text[:200]}",
    )
    if assessment.status_code != 201:  # pragma: no cover
        return case

    advice = assessment.json()
    case.inputs["irrigation_assessment_id"] = advice["id"]
    case.inputs["decision_body"] = {
        "status": "approved",
        "reviewer_name": "Priya Raghavan (Agronomist)",
        "decision_note": "Reviewed on site; soil moisture probe checked against a hand check.",
    }

    case.expect("Recommendation", advice["recommendation"], predicate=bool)
    case.expect("Urgency", advice["urgency"], predicate=bool)
    case.expect("requires_human_authorisation", advice["requires_human_authorisation"], predicate=bool)
    case.expect("authorisation_state before review", advice["authorisation_state"])
    case.expect("Estimated depth (mm)", advice["estimated_water_mm"], predicate=lambda v: v is None or v > 0)
    case.expect("Estimated volume (m3)", advice["estimated_volume_m3"], predicate=lambda v: v is None or v > 0)
    case.expect("Rules evaluated", [r.get("rule") or r.get("name") for r in advice["rules_evaluated"]])

    case.check(
        "Irrigation advice is explicitly unauthorised",
        advice["requires_human_authorisation"] is True and advice["authorisation_state"] == "not_authorised",
        f"{advice['requires_human_authorisation']}/{advice['authorisation_state']}",
    )

    contract = client.get(f"{API}/approvals/safety-contract").json()
    case.expect("Safety contract - approved", contract["approved"], predicate=bool)
    case.expect("Safety contract - never", contract["never"], predicate=bool)
    case.check(
        "Safety contract denies any physical actuation path",
        "no code path" in contract["never"].lower() and "physical" in contract["never"].lower(),
        contract["never"],
    )

    # --- a full run must park at human review, not execute irrigation ----
    summary = _run_workflow(client, field_id)
    case.inputs["workflow_run_id"] = summary["workflow_run_id"]
    run_status = summary["status"]
    approval = summary.get("approval") or {}

    case.expect("Workflow run status", run_status)
    case.expect("Approval status", approval.get("status"))
    case.expect("Approval reviewer", approval.get("reviewer_name") or "(unassigned)")
    case.check(
        "Run halts at awaiting_human_review",
        run_status == "awaiting_human_review",
        run_status,
    )
    case.check(
        "A pending approval request was raised",
        approval.get("status") == "pending" and bool(approval.get("id")),
        f"approval={approval.get('id')} status={approval.get('status')}",
    )

    before = {
        item["activity_type"]: item["status"]
        for item in client.get(f"{API}/activities", params={"field_id": field_id}).json()
    }
    case.inputs["activities_before_approval"] = before
    case.check(
        "No irrigation activity is scheduled before approval",
        before.get("irrigation", "absent") in {"planned", "absent"},
        f"irrigation activity status = {before.get('irrigation', 'absent')}",
    )

    # --- a named human approves ------------------------------------------
    approval_id = int(approval["id"])
    decision = client.post(
        f"{API}/approvals/{approval_id}/decision",
        json={
            "status": "approved",
            "reviewer_name": "Priya Raghavan (Agronomist)",
            "decision_note": "Reviewed on site; probe cross-checked by hand.",
        },
    )
    case.check(
        "Approval decision accepted",
        decision.status_code == 200,
        f"HTTP {decision.status_code} {decision.text[:200]}",
    )
    if decision.status_code == 200:
        decided = decision.json()
        case.expect("Approval status after decision", decided["status"])
        case.expect("Reviewer recorded", decided["reviewer_name"], predicate=bool)
        case.expect("Decision timestamp", decided["decided_at"], predicate=bool)

    after = {
        item["activity_type"]: (item["status"], item["responsible_person"])
        for item in client.get(f"{API}/activities", params={"field_id": field_id}).json()
    }
    case.inputs["activities_after_approval"] = after
    case.expect("Irrigation activity after approval", after.get("irrigation"), predicate=bool)

    if decision.status_code == 200:
        case.check(
            "Approval schedules the irrigation activity (planned -> scheduled)",
            after.get("irrigation", ("", ""))[0] == "scheduled",
            f"status={after.get('irrigation', ('absent',))[0]}",
        )
        case.check(
            "Accountable person is recorded on the scheduled activity",
            bool(after.get("irrigation", ("", ""))[1]),
            f"responsible_person={after.get('irrigation', ('.', ''))[1]}",
        )

    final = client.get(f"{API}/workflow/runs/{summary['workflow_run_id']}/summary").json()
    case.expect("Run status after approval", final["status"])
    case.check(
        "Run completes once the human gate is cleared",
        final["status"] == "completed",
        final["status"],
    )

    case.agents_invoked = [
        name for name in final["agents_invoked"] if name in {"irrigation", "activity_planner", "ml_forecast"}
    ] or ["irrigation", "activity_planner"]
    case.evidence = evidence_digest(advice["evidence"])
    case.sources = source_digest(advice["sources"])
    case.notes = (
        "Approval authorises the recorded plan only. There is no irrigation-hardware adapter in the codebase: "
        "the deepest effect of a decision is FarmActivity.status changing from 'planned' to 'scheduled'."
    )
    return case


# ======================================================================
# TC-05 - risk wording is favourable-environment, never a diagnosis
# ======================================================================
def test_tc05_risk_wording_and_ml_cross_check(client, field_id: int) -> CaseResult:
    case = CaseResult(
        case_id="TC-05",
        title="Crop risk is reported as favourable environment and cross-checked by a trained model",
        requirement=(
            "Risk findings must be phrased as 'Environmental conditions favourable for X'. The system must "
            "never claim a disease is confirmed, must declare its non-diagnostic disclaimer, and must agree "
            "with the trained ML severity model."
        ),
        inputs={"GET": [f"{API}/risk/fields/{field_id}", f"{API}/risk/disclaimer"]},
        expected=[
            "Findings are phrased 'Environmental conditions favourable for ...'.",
            "No finding contains a confirmation or diagnosis phrase.",
            "Every persisted finding carries is_diagnosis=false.",
            "A non-diagnostic disclaimer is returned alongside the findings.",
            "The trained risk classifier agrees with the rule-based severity, or the disagreement is reported.",
            "Each finding cites the evidence it was derived from.",
        ],
    )

    response = client.get(f"{API}/risk/fields/{field_id}")
    case.check("Risk scan returns 200", response.status_code == 200, f"HTTP {response.status_code}")
    if response.status_code != 200:  # pragma: no cover
        return case

    body = response.json()
    findings = body["findings"]
    disclaimer = client.get(f"{API}/risk/disclaimer").json()
    case.inputs["finding_count"] = len(findings)

    case.expect("Overall risk level", body["risk_level"], predicate=bool)
    case.expect("Disclaimer", body["disclaimer"], predicate=lambda v: "no diagnostic" in v.lower())
    case.expect(
        "Finding statements",
        [item["statement"] for item in findings],
        predicate=bool,
    )
    case.expect(
        "Severities",
        [f"{item['risk_type']}={item['severity']}" for item in findings],
        predicate=bool,
    )

    case.check(
        f"Every finding uses '{FAVOURABLE_PREFIX} ...'",
        all(item["statement"].startswith(FAVOURABLE_PREFIX) for item in findings),
        f"{sum(1 for i in findings if i['statement'].startswith(FAVOURABLE_PREFIX))}/{len(findings)}",
    )

    haystack = _text_blob(findings)
    hits = [phrase for phrase in FORBIDDEN_DIAGNOSTIC_PHRASES if phrase in haystack]
    case.check(
        "No confirmation / diagnosis language anywhere in the findings",
        not hits,
        f"forbidden phrases found: {hits}" if hits else "none found",
    )
    case.check(
        "Every persisted finding is flagged is_diagnosis=false",
        all(item["is_diagnosis"] is False for item in findings),
        f"{sum(1 for i in findings if i['is_diagnosis'] is False)}/{len(findings)}",
    )
    case.check(
        "Disclaimer endpoint publishes the wording rule",
        "favourable for" in disclaimer["wording_rule"].lower() and "never states" in disclaimer["wording_rule"].lower(),
        disclaimer["wording_rule"][:120],
    )
    case.check(
        "Every finding tells the reader what to check next",
        all((item["recommended_investigation"] or "").strip() for item in findings),
        f"{sum(1 for i in findings if (i['recommended_investigation'] or '').strip())}/{len(findings)}",
    )
    disease_findings = [item for item in findings if "disease" in item["risk_type"]]
    case.check(
        "Disease-environment findings route to scouting plus lab/plant-clinic confirmation",
        all(
            "scout" in (item["recommended_investigation"] or "").lower()
            and (
                "laborator" in (item["recommended_investigation"] or "").lower()
                or "clinic" in (item["recommended_investigation"] or "").lower()
            )
            for item in disease_findings
        ),
        f"{len(disease_findings)} disease-environment finding(s)",
    )

    # --- ML cross-check -------------------------------------------------
    prediction = client.post(f"{API}/ml/predict", params={"field_id": field_id})
    case.check(
        "ML scoring endpoint runs with no request body",
        prediction.status_code in {200, 201},
        f"HTTP {prediction.status_code} {prediction.text[:200]}",
    )
    if prediction.status_code in {200, 201}:
        rows = prediction.json()
        ml = next((row for row in rows if row["task"] == MLTask_RISK), None)
        case.check(
            "Both trained models answered",
            len(rows) == 2 and ml is not None,
            f"{[row['task'] for row in rows]}",
        )
        if ml is None:  # pragma: no cover
            return case
        case.inputs["ml_risk_prediction"] = {
            "model_name": ml["model_name"],
            "prediction_label": ml["prediction_label"],
            "confidence": ml["confidence"],
        }
        case.expect("ML model", ml["model_name"], predicate=bool)
        case.expect("ML predicted severity", ml["prediction_label"], predicate=bool)
        case.expect("ML confidence", ml["confidence"], predicate=lambda v: v is not None and 0.0 <= v <= 1.0)
        case.check(
            "ML prediction is attributed to the trained model, not invented",
            ml["model_metadata"].get("trained_at") is not None and bool(ml["model_metadata"].get("target")),
            f"target={ml['model_metadata'].get('target')}",
        )
        case.expect(
            "ML features actually fed to the model",
            sorted(ml["features"])[:6],
            predicate=bool,
        )

        rank = {"none": 0, "info": 0, "low": 1, "medium": 2, "high": 3, "severe": 3}
        worst_rule = max((rank.get(item["severity"], 1) for item in findings), default=0)
        worst_ml = rank.get(str(ml["prediction_label"]).lower(), 1)
        agree = abs(worst_rule - worst_ml) <= 1
        case.expect(
            "Rule-based worst severity",
            [item["severity"] for item in findings],
            predicate=bool,
        )
        case.check(
            "ML severity agrees with the rule-based scan within one band",
            agree,
            f"rules={worst_rule} ml={worst_ml}",
        )
        case.agents_invoked = ["crop_risk_advisory", "ml_forecast", "knowledge_retrieval"]

    case.sources = source_digest([source for item in findings for source in item["sources"]])
    case.evidence = evidence_digest([ev for item in findings for ev in item["evidence"]])
    case.notes = (
        "Risk statements describe the environment only. Confirming a disease needs field scouting or a "
        "laboratory test, which is exactly what recommended_investigation tells the reader to do."
    )
    return case


# ======================================================================
# TC-06 - the full orchestrated run: 12 agents, RAG citations, PDF
# ======================================================================
def test_tc06_full_orchestration_rag_and_pdf(client, field_id: int) -> CaseResult:
    case = CaseResult(
        case_id="TC-06",
        title="Full multi-agent orchestration with retrieved citations and a downloadable PDF report",
        requirement=(
            "A single request must drive the whole LangGraph workflow, all specialised agents must run, "
            "their citations and evidence must reach the run summary, and the generated PDF report must be "
            "a real, openable file."
        ),
        inputs={
            "POST": f"{API}/workflow/runs",
            "body": {"field_id": field_id, "crop": "cotton", "force_refresh_weather": True},
        },
        expected=[
            "All 12 agents in the graph report status 'succeeded'.",
            "The run summary carries the merged evidence ledger and the retrieved citations.",
            "The activity planner produced dated activities.",
            "The alert agent raised de-duplicated alerts.",
            "A PDF report is generated, is a valid PDF, has pages and downloads over HTTP.",
            "The PDF contains the non-diagnostic risk wording and the reference list.",
        ],
    )

    expected_agents = {
        "farm_field_profile",
        "soil_nutrient",
        "sensor_telemetry",
        "weather_climate",
        "weather_bundle_bridge",
        "knowledge_retrieval",
        "crop_suitability",
        "ml_forecast",
        "irrigation",
        "crop_risk_advisory",
        "activity_planner",
        "advisory_narrative",
    }

    summary = _run_workflow(client, field_id)
    run_id = int(summary["workflow_run_id"])
    case.inputs["workflow_run_id"] = run_id

    detail = client.get(f"{API}/workflow/runs/{run_id}").json()
    traces = detail["traces"]
    case.inputs["traces"] = [{"agent": t["agent_name"], "status": t["status"], "ms": t["duration_ms"]} for t in traces]

    invoked = set(summary["agents_invoked"])
    succeeded = {t["agent_name"] for t in traces if t["status"] == "succeeded"}

    case.expect("Agents recorded on the run", sorted(summary["agents_invoked"]), predicate=bool)
    case.expect("Overall run status", summary["status"])
    case.expect("Suitability score", (summary.get("suitability") or {}).get("score"))
    case.expect("Risk level", summary["risk_level"])
    case.expect("ML predictions", [p["task"] for p in summary["ml_predictions"]], predicate=bool)
    case.expect("Alerts raised", [f"{a['alert_type']}/{a['severity']}" for a in summary["alerts"]])
    case.expect(
        "Activities planned",
        [f"{a['activity_type']}:{a['status']}" for a in summary["activities"]],
        predicate=bool,
    )
    case.expect("Citations in summary", [s["doc_key"] for s in summary["sources"]], predicate=bool)

    case.check(
        f"All {len(expected_agents)} specialised agents ran",
        expected_agents <= invoked,
        f"missing: {sorted(expected_agents - invoked) or 'none'}",
    )
    case.check(
        "Every agent trace reports 'succeeded'",
        expected_agents <= succeeded,
        f"not succeeded: {sorted(expected_agents - succeeded) or 'none'}",
    )
    case.check(
        "No agent trace recorded an error",
        all(not t["error"] for t in traces),
        f"errors: {[t['error'] for t in traces if t['error']] or 'none'}",
    )
    case.check(
        "Every agent trace is timestamped and timed",
        all(t["duration_ms"] is not None for t in traces),
        f"{len(traces)} traces",
    )
    case.check(
        "Run warnings, if any, are explained",
        all(w for w in summary["warnings"]),
        f"{len(summary['warnings'])} warning(s)",
    )

    sources = summary["sources"]
    evidence = summary["evidence"]
    case.check(
        "Citations from FAISS retrieval reach the run summary",
        len(sources) >= 3,
        f"{len(sources)} citation(s)",
    )
    case.check(
        "Evidence ledger from every agent is merged (not overwritten)",
        len(evidence) >= 15,
        f"{len(evidence)} evidence row(s)",
    )
    case.check(
        "Evidence rows carry provenance tags",
        {item["kind"] for item in evidence} >= {"measured", "forecast", "retrieved_reference"},
        f"kinds={sorted({item['kind'] for item in evidence})}",
    )
    case.check(
        "Citations are de-duplicated by document",
        len({item["doc_key"] for item in sources}) == len(sources),
        f"{len({item['doc_key'] for item in sources})} unique of {len(sources)}",
    )
    case.check(
        "The activity planner produced dated activities",
        bool(summary["activities"]) and any(a["scheduled_date"] for a in summary["activities"]),
        f"{len(summary['activities'])} activities",
    )

    if summary["alerts"]:
        fingerprints = [a["fingerprint"] for a in summary["alerts"]]
        case.check(
            "Alerts are de-duplicated by fingerprint",
            len(set(fingerprints)) == len(fingerprints),
            f"{len(set(fingerprints))} unique of {len(fingerprints)}",
        )

    # --- PDF ------------------------------------------------------------
    report_response = client.post(f"{API}/reports", params={"field_id": field_id}, json={"workflow_run_id": run_id})
    case.check(
        "Report generation accepted",
        report_response.status_code == 201,
        f"HTTP {report_response.status_code} {report_response.text[:200]}",
    )
    if report_response.status_code != 201:  # pragma: no cover
        case.status = "FAIL"
        return case

    report = report_response.json()
    report_id = int(report["id"])
    case.inputs["report_id"] = report_id

    case.expect("Report status", report["status"])
    case.expect("Report file name", report["file_name"], predicate=bool)
    case.expect("Report size (bytes)", report["size_bytes"], predicate=lambda v: v and v > 1_000)
    case.expect("Report pages", report["page_count"], predicate=lambda v: v and v >= 1)
    case.expect("Sections", report["section_summary"]["sections"], predicate=bool)
    case.expect("Download URL", report["download_url"], predicate=bool)

    case.check(
        "Report rendered successfully",
        report["status"] == "ready" and not report["error"],
        f"status={report['status']} error={report['error']}",
    )
    case.check(
        "download_url is a real route",
        report["download_url"] == f"{API}/reports/{report_id}/download",
        str(report["download_url"]),
    )

    download = client.get(f"{API}/reports/{report_id}/download")
    case.check(
        "PDF downloads over HTTP",
        download.status_code == 200,
        f"HTTP {download.status_code}",
    )
    if download.status_code == 200:
        blob = download.content
        case.check(
            "Download is a real PDF (magic header)",
            blob[:5] == b"%PDF-",
            repr(blob[:8]),
        )
        case.check(
            "PDF is not an empty stub",
            len(blob) == report["size_bytes"] and len(blob) > 5_000,
            f"{len(blob)} bytes",
        )

        on_disk = Path(settings.reports_dir) / report["file_name"]
        case.check(
            "PDF exists on disk",
            on_disk.is_file(),
            str(on_disk),
        )
        if on_disk.is_file():
            case.check(
                "File on disk matches the downloaded bytes",
                on_disk.read_bytes()[:5] == b"%PDF-",
                repr(on_disk.read_bytes()[:8]),
            )

        text = ""
        try:
            from pypdf import PdfReader

            reader = PdfReader(io.BytesIO(blob))
            text = "\n".join(page.extract_text() or "" for page in reader.pages)
            case.check(
                "PDF page count matches the recorded metadata",
                len(reader.pages) == report["page_count"],
                f"reader={len(reader.pages)} recorded={report['page_count']}",
            )
        except ImportError:  # pragma: no cover - pypdf is a declared dependency
            case.check("pypdf is installed for report verification", False, "pypdf missing")

        if text:
            case.expect("PDF characters extracted", len(text), predicate=lambda n: n > 800)
            case.check(
                "PDF uses the non-diagnostic risk wording",
                FAVOURABLE_PREFIX.lower() in text.lower(),
                f"'{FAVOURABLE_PREFIX}' present={FAVOURABLE_PREFIX.lower() in text.lower()}",
            )
            case.check(
                "PDF contains a references section",
                "reference" in text.lower(),
                "references heading found",
            )
            case.check(
                "PDF contains a limitations section",
                "limitation" in text.lower(),
                "limitations heading found",
            )
            case.check(
                "PDF contains no confirmation language",
                not [p for p in FORBIDDEN_DIAGNOSTIC_PHRASES if p in text.lower()],
                "no forbidden phrases",
            )
            case.check(
                "PDF names the field that was analysed",
                summary["field_name"].split()[0].lower() in text.lower(),
                summary["field_name"],
            )

    case.agents_invoked = sorted(invoked)
    case.sources = source_digest(sources)
    case.evidence = evidence_digest(evidence, limit=12)
    case.notes = (
        "The run is driven by LangGraph with an explicit WorkflowState; every node's evidence and citations "
        "are merged into that state, so the summary and the PDF are built from the same ledger the agents wrote."
    )
    return case


# ======================================================================
# Collection: run all six, then write the record
# ======================================================================
def test_record_all_acceptance_cases(client, field_id: int) -> None:
    payload = write_report(
        [
            test_tc01_farm_and_soil_profile(client, field_id),
            test_tc02_weather_live_or_labelled_fallback(client, field_id),
            test_tc03_crop_suitability_factors_and_citations(client, field_id),
            test_tc04_irrigation_requires_human_approval(client, field_id),
            test_tc05_risk_wording_and_ml_cross_check(client, field_id),
            test_tc06_full_orchestration_rag_and_pdf(client, field_id),
        ]
    )
    assert payload["failed"] == 0, (
        f"{payload['failed']} acceptance case(s) failed: "
        f"{[case['case_id'] for case in payload['cases'] if case['status'] != 'PASS']}"
    )
    assert payload["total_cases"] == 6
    assert payload["total_checks"] > 60
