"""initial precision farming schema

Revision ID: 825e0dc52cb1
Revises:
Create Date: 2026-10-04 12:53:43.513195

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Custom column types (UTCDateTime, JSONDict) are rendered by repr(), so this
# import must stay in every generated migration.
import app.models.base

revision: str = "825e0dc52cb1"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "farms",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("owner_name", sa.String(length=120), nullable=False),
        sa.Column("location_name", sa.String(length=160), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("village", sa.String(length=120), nullable=True),
        sa.Column("district", sa.String(length=120), nullable=True),
        sa.Column("state", sa.String(length=120), nullable=True),
        sa.Column("total_area_ha", sa.Float(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", app.models.base.UTCDateTime(), nullable=False),
        sa.Column("updated_at", app.models.base.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("farms", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_farms_name"), ["name"], unique=False)

    op.create_table(
        "reference_documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("doc_key", sa.String(length=120), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column("organisation", sa.String(length=120), nullable=False),
        sa.Column("source_url", sa.String(length=400), nullable=True),
        sa.Column("region", sa.String(length=120), nullable=True),
        sa.Column("chunk_count", sa.Integer(), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", app.models.base.UTCDateTime(), nullable=False),
        sa.Column("updated_at", app.models.base.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("doc_key"),
    )
    with op.batch_alter_table("reference_documents", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_reference_documents_category"), ["category"], unique=False)

    op.create_table(
        "fields",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("farm_id", sa.Integer(), nullable=False),
        sa.Column("field_code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("area_ha", sa.Float(), nullable=False),
        sa.Column("soil_type", sa.String(length=40), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("previous_crop", sa.String(length=64), nullable=True),
        sa.Column("proposed_crop", sa.String(length=64), nullable=True),
        sa.Column("crop_stage", sa.String(length=32), nullable=False),
        sa.Column("planting_window_start", app.models.base.UTCDateTime(), nullable=True),
        sa.Column("irrigation_source", sa.String(length=32), nullable=False),
        sa.Column("water_availability", sa.String(length=32), nullable=False),
        sa.Column("water_availability_m3_per_day", sa.Float(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", app.models.base.UTCDateTime(), nullable=False),
        sa.Column("updated_at", app.models.base.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(["farm_id"], ["farms.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("fields", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_fields_farm_id"), ["farm_id"], unique=False)
        batch_op.create_index("ix_fields_farm_id_code", ["farm_id", "field_code"], unique=True)

    op.create_table(
        "alerts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("farm_id", sa.Integer(), nullable=False),
        sa.Column("field_id", sa.Integer(), nullable=False),
        sa.Column("alert_type", sa.String(length=48), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("evidence", app.models.types.JSONDict(), nullable=False),
        sa.Column("fingerprint", sa.String(length=160), nullable=False),
        sa.Column("severity_rank", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("occurrence_count", sa.Integer(), nullable=False),
        sa.Column("triggered_at", app.models.base.UTCDateTime(), nullable=False),
        sa.Column("last_observed_at", app.models.base.UTCDateTime(), nullable=False),
        sa.Column("acknowledged_at", app.models.base.UTCDateTime(), nullable=True),
        sa.Column("acknowledged_by", sa.String(length=120), nullable=True),
        sa.Column("resolved_at", app.models.base.UTCDateTime(), nullable=True),
        sa.Column("created_at", app.models.base.UTCDateTime(), nullable=False),
        sa.Column("updated_at", app.models.base.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(["farm_id"], ["farms.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["field_id"], ["fields.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("alerts", schema=None) as batch_op:
        batch_op.create_index("ix_alert_field_fingerprint_status", ["field_id", "fingerprint", "status"], unique=False)
        batch_op.create_index(batch_op.f("ix_alerts_farm_id"), ["farm_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_alerts_field_id"), ["field_id"], unique=False)

    op.create_table(
        "sensor_readings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("field_id", sa.Integer(), nullable=False),
        sa.Column("sensor_id", sa.String(length=64), nullable=False),
        sa.Column("recorded_at", app.models.base.UTCDateTime(), nullable=False),
        sa.Column("soil_moisture_percent", sa.Float(), nullable=True),
        sa.Column("soil_temperature_c", sa.Float(), nullable=True),
        sa.Column("air_humidity_percent", sa.Float(), nullable=True),
        sa.Column("air_temperature_c", sa.Float(), nullable=True),
        sa.Column("battery_percent", sa.Float(), nullable=True),
        sa.Column("is_simulated", sa.Boolean(), nullable=False),
        sa.Column("quality_flags", app.models.types.JSONDict(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", app.models.base.UTCDateTime(), nullable=False),
        sa.Column("updated_at", app.models.base.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(["field_id"], ["fields.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sensor_readings", schema=None) as batch_op:
        batch_op.create_index("ix_sensor_reading_field_time", ["field_id", "recorded_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_sensor_readings_field_id"), ["field_id"], unique=False)

    op.create_table(
        "soil_observations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("field_id", sa.Integer(), nullable=False),
        sa.Column("observed_at", app.models.base.UTCDateTime(), nullable=False),
        sa.Column("sample_depth_cm", sa.Float(), nullable=True),
        sa.Column("soil_type", sa.String(length=40), nullable=True),
        sa.Column("ph", sa.Float(), nullable=True),
        sa.Column("nitrogen_available_kg_ha", sa.Float(), nullable=True),
        sa.Column("phosphorus_available_kg_ha", sa.Float(), nullable=True),
        sa.Column("potassium_available_kg_ha", sa.Float(), nullable=True),
        sa.Column("organic_carbon_percent", sa.Float(), nullable=True),
        sa.Column("soil_moisture_percent", sa.Float(), nullable=True),
        sa.Column("electrical_conductivity_ds_m", sa.Float(), nullable=True),
        sa.Column("data_source", sa.String(length=32), nullable=False),
        sa.Column("lab_name", sa.String(length=160), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", app.models.base.UTCDateTime(), nullable=False),
        sa.Column("updated_at", app.models.base.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(["field_id"], ["fields.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("soil_observations", schema=None) as batch_op:
        batch_op.create_index("ix_soil_observation_field_observed", ["field_id", "observed_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_soil_observations_field_id"), ["field_id"], unique=False)

    op.create_table(
        "water_balance_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("field_id", sa.Integer(), nullable=False),
        sa.Column("applied_on", app.models.base.UTCDateTime(), nullable=False),
        sa.Column("depth_mm", sa.Float(), nullable=False),
        sa.Column("volume_m3", sa.Float(), nullable=True),
        sa.Column("method", sa.String(length=48), nullable=False),
        sa.Column("applied_by", sa.String(length=120), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", app.models.base.UTCDateTime(), nullable=False),
        sa.Column("updated_at", app.models.base.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(["field_id"], ["fields.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("water_balance_records", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_water_balance_records_field_id"), ["field_id"], unique=False)
        batch_op.create_index("ix_water_field_applied", ["field_id", "applied_on"], unique=False)

    op.create_table(
        "weather_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("field_id", sa.Integer(), nullable=False),
        sa.Column("farm_id", sa.Integer(), nullable=True),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("is_simulated", sa.Boolean(), nullable=False),
        sa.Column("fetched_at", app.models.base.UTCDateTime(), nullable=False),
        sa.Column("observed_at", app.models.base.UTCDateTime(), nullable=True),
        sa.Column("temperature_c", sa.Float(), nullable=True),
        sa.Column("feels_like_c", sa.Float(), nullable=True),
        sa.Column("humidity_percent", sa.Float(), nullable=True),
        sa.Column("wind_speed_ms", sa.Float(), nullable=True),
        sa.Column("condition", sa.String(length=120), nullable=True),
        sa.Column("forecast_date", app.models.base.UTCDateTime(), nullable=True),
        sa.Column("temp_min_c", sa.Float(), nullable=True),
        sa.Column("temp_max_c", sa.Float(), nullable=True),
        sa.Column("precipitation_mm", sa.Float(), nullable=True),
        sa.Column("precipitation_probability_percent", sa.Float(), nullable=True),
        sa.Column("et0_mm", sa.Float(), nullable=True),
        sa.Column("raw_payload", app.models.types.JSONDict(), nullable=True),
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.Column("created_at", app.models.base.UTCDateTime(), nullable=False),
        sa.Column("updated_at", app.models.base.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(["farm_id"], ["farms.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["field_id"], ["fields.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("weather_snapshots", schema=None) as batch_op:
        batch_op.create_index("ix_weather_snapshot_field_date", ["field_id", "forecast_date"], unique=False)
        batch_op.create_index(batch_op.f("ix_weather_snapshots_farm_id"), ["farm_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_weather_snapshots_field_id"), ["field_id"], unique=False)

    op.create_table(
        "workflow_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("farm_id", sa.Integer(), nullable=False),
        sa.Column("field_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("current_step", sa.String(length=64), nullable=True),
        sa.Column("crop", sa.String(length=64), nullable=True),
        sa.Column("state", app.models.types.JSONDict(), nullable=False),
        sa.Column("agents_invoked", app.models.types.JSONDict(), nullable=False),
        sa.Column("warnings", app.models.types.JSONDict(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("completed_at", app.models.base.UTCDateTime(), nullable=True),
        sa.Column("duration_ms", sa.Float(), nullable=True),
        sa.Column("created_at", app.models.base.UTCDateTime(), nullable=False),
        sa.Column("updated_at", app.models.base.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(["farm_id"], ["farms.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["field_id"], ["fields.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("workflow_runs", schema=None) as batch_op:
        batch_op.create_index("ix_workflow_field_created", ["field_id", "created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_workflow_runs_farm_id"), ["farm_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_workflow_runs_field_id"), ["field_id"], unique=False)

    op.create_table(
        "agent_traces",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workflow_run_id", sa.Integer(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("agent_name", sa.String(length=80), nullable=False),
        sa.Column("responsibility", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("input_summary", app.models.types.JSONDict(), nullable=False),
        sa.Column("output", app.models.types.JSONDict(), nullable=False),
        sa.Column("evidence", app.models.types.JSONDict(), nullable=False),
        sa.Column("sources", app.models.types.JSONDict(), nullable=False),
        sa.Column("reasoning", sa.Text(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("duration_ms", sa.Float(), nullable=True),
        sa.Column("model_used", sa.String(length=64), nullable=True),
        sa.Column("created_at", app.models.base.UTCDateTime(), nullable=False),
        sa.Column("updated_at", app.models.base.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(["workflow_run_id"], ["workflow_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("agent_traces", schema=None) as batch_op:
        batch_op.create_index("ix_agent_trace_run_sequence", ["workflow_run_id", "sequence"], unique=False)

    op.create_table(
        "approval_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workflow_run_id", sa.Integer(), nullable=False),
        sa.Column("field_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("action_type", sa.String(length=48), nullable=False),
        sa.Column("recommendation", app.models.types.JSONDict(), nullable=False),
        sa.Column("evidence", app.models.types.JSONDict(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("reviewer_name", sa.String(length=120), nullable=True),
        sa.Column("decision_note", sa.Text(), nullable=True),
        sa.Column("modified_action", app.models.types.JSONDict(), nullable=True),
        sa.Column("observation", sa.Text(), nullable=True),
        sa.Column("reanalysis_requested", sa.Boolean(), nullable=False),
        sa.Column("decided_at", app.models.base.UTCDateTime(), nullable=True),
        sa.Column("created_at", app.models.base.UTCDateTime(), nullable=False),
        sa.Column("updated_at", app.models.base.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(["field_id"], ["fields.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workflow_run_id"], ["workflow_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("approval_requests", schema=None) as batch_op:
        batch_op.create_index("ix_approval_field_status", ["field_id", "status"], unique=False)
        batch_op.create_index(batch_op.f("ix_approval_requests_field_id"), ["field_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_approval_requests_workflow_run_id"), ["workflow_run_id"], unique=False)

    op.create_table(
        "irrigation_assessments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("field_id", sa.Integer(), nullable=False),
        sa.Column("workflow_run_id", sa.Integer(), nullable=True),
        sa.Column("recommendation", sa.String(length=48), nullable=False),
        sa.Column("urgency", sa.String(length=24), nullable=False),
        sa.Column("requires_human_authorisation", sa.Boolean(), nullable=False),
        sa.Column("authorisation_state", sa.String(length=32), nullable=False),
        sa.Column("estimated_water_mm", sa.Float(), nullable=True),
        sa.Column("estimated_volume_m3", sa.Float(), nullable=True),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("rules_evaluated", app.models.types.JSONDict(), nullable=False),
        sa.Column("sensor_context", app.models.types.JSONDict(), nullable=False),
        sa.Column("weather_context", app.models.types.JSONDict(), nullable=False),
        sa.Column("ml_prediction", app.models.types.JSONDict(), nullable=False),
        sa.Column("evidence", app.models.types.JSONDict(), nullable=False),
        sa.Column("sources", app.models.types.JSONDict(), nullable=False),
        sa.Column("generated_by", sa.String(length=32), nullable=False),
        sa.Column("created_at", app.models.base.UTCDateTime(), nullable=False),
        sa.Column("updated_at", app.models.base.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(["field_id"], ["fields.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workflow_run_id"], ["workflow_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("irrigation_assessments", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_irrigation_assessments_field_id"), ["field_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_irrigation_assessments_workflow_run_id"), ["workflow_run_id"], unique=False
        )
        batch_op.create_index("ix_irrigation_field_created", ["field_id", "created_at"], unique=False)

    op.create_table(
        "ml_predictions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("field_id", sa.Integer(), nullable=False),
        sa.Column("workflow_run_id", sa.Integer(), nullable=True),
        sa.Column("model_name", sa.String(length=80), nullable=False),
        sa.Column("model_version", sa.String(length=32), nullable=False),
        sa.Column("task", sa.String(length=48), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("prediction_value", sa.Float(), nullable=True),
        sa.Column("prediction_label", sa.String(length=64), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("features", app.models.types.JSONDict(), nullable=False),
        sa.Column("model_metadata", app.models.types.JSONDict(), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("created_at", app.models.base.UTCDateTime(), nullable=False),
        sa.Column("updated_at", app.models.base.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(["field_id"], ["fields.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workflow_run_id"], ["workflow_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("ml_predictions", schema=None) as batch_op:
        batch_op.create_index("ix_ml_field_created", ["field_id", "created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_ml_predictions_field_id"), ["field_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_ml_predictions_workflow_run_id"), ["workflow_run_id"], unique=False)

    op.create_table(
        "reports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("farm_id", sa.Integer(), nullable=False),
        sa.Column("field_id", sa.Integer(), nullable=False),
        sa.Column("workflow_run_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("file_name", sa.String(length=240), nullable=True),
        sa.Column("file_path", sa.String(length=400), nullable=True),
        sa.Column("size_bytes", sa.Integer(), nullable=True),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("section_summary", app.models.types.JSONDict(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", app.models.base.UTCDateTime(), nullable=False),
        sa.Column("updated_at", app.models.base.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(["farm_id"], ["farms.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["field_id"], ["fields.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workflow_run_id"], ["workflow_runs.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_reports_farm_id"), ["farm_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_reports_field_id"), ["field_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_reports_workflow_run_id"), ["workflow_run_id"], unique=False)

    op.create_table(
        "risk_findings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("field_id", sa.Integer(), nullable=False),
        sa.Column("workflow_run_id", sa.Integer(), nullable=True),
        sa.Column("risk_type", sa.String(length=48), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("statement", sa.Text(), nullable=False),
        sa.Column("potential_impact", sa.Text(), nullable=True),
        sa.Column("recommended_investigation", sa.Text(), nullable=True),
        sa.Column("evidence", app.models.types.JSONDict(), nullable=False),
        sa.Column("sources", app.models.types.JSONDict(), nullable=False),
        sa.Column("observed_at", app.models.base.UTCDateTime(), nullable=False),
        sa.Column("is_diagnosis", sa.Boolean(), nullable=False),
        sa.Column("created_at", app.models.base.UTCDateTime(), nullable=False),
        sa.Column("updated_at", app.models.base.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(["field_id"], ["fields.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workflow_run_id"], ["workflow_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("risk_findings", schema=None) as batch_op:
        batch_op.create_index("ix_risk_field_created", ["field_id", "created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_risk_findings_field_id"), ["field_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_risk_findings_workflow_run_id"), ["workflow_run_id"], unique=False)

    op.create_table(
        "soil_interpretations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("soil_observation_id", sa.Integer(), nullable=False),
        sa.Column("agent_name", sa.String(length=80), nullable=False),
        sa.Column("generated_by", sa.String(length=32), nullable=False),
        sa.Column("ph_class", sa.String(length=32), nullable=False),
        sa.Column("nutrient_status", app.models.types.JSONDict(), nullable=False),
        sa.Column("organic_matter_status", sa.String(length=32), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("limitations", app.models.types.JSONDict(), nullable=False),
        sa.Column("recommendations", app.models.types.JSONDict(), nullable=False),
        sa.Column("missing_parameters", app.models.types.JSONDict(), nullable=False),
        sa.Column("evidence", app.models.types.JSONDict(), nullable=False),
        sa.Column("sources", app.models.types.JSONDict(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("created_at", app.models.base.UTCDateTime(), nullable=False),
        sa.Column("updated_at", app.models.base.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(["soil_observation_id"], ["soil_observations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("soil_observation_id"),
    )
    op.create_table(
        "suitability_assessments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("field_id", sa.Integer(), nullable=False),
        sa.Column("workflow_run_id", sa.Integer(), nullable=True),
        sa.Column("crop", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=48), nullable=False),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("factor_scores", app.models.types.JSONDict(), nullable=False),
        sa.Column("favorable_factors", app.models.types.JSONDict(), nullable=False),
        sa.Column("limiting_factors", app.models.types.JSONDict(), nullable=False),
        sa.Column("missing_information", app.models.types.JSONDict(), nullable=False),
        sa.Column("requirements_used", app.models.types.JSONDict(), nullable=False),
        sa.Column("evidence", app.models.types.JSONDict(), nullable=False),
        sa.Column("sources", app.models.types.JSONDict(), nullable=False),
        sa.Column("narrative", sa.Text(), nullable=True),
        sa.Column("generated_by", sa.String(length=32), nullable=False),
        sa.Column("created_at", app.models.base.UTCDateTime(), nullable=False),
        sa.Column("updated_at", app.models.base.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(["field_id"], ["fields.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workflow_run_id"], ["workflow_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("suitability_assessments", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_suitability_assessments_field_id"), ["field_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_suitability_assessments_workflow_run_id"), ["workflow_run_id"], unique=False
        )
        batch_op.create_index("ix_suitability_field_created", ["field_id", "created_at"], unique=False)

    op.create_table(
        "farm_activities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("field_id", sa.Integer(), nullable=False),
        sa.Column("workflow_run_id", sa.Integer(), nullable=True),
        sa.Column("approval_request_id", sa.Integer(), nullable=True),
        sa.Column("activity_type", sa.String(length=48), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("scheduled_date", app.models.base.UTCDateTime(), nullable=True),
        sa.Column("window_days", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("responsible_person", sa.String(length=120), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("priority", sa.String(length=16), nullable=False),
        sa.Column("evidence", app.models.types.JSONDict(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", app.models.base.UTCDateTime(), nullable=False),
        sa.Column("updated_at", app.models.base.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(["approval_request_id"], ["approval_requests.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["field_id"], ["fields.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workflow_run_id"], ["workflow_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("farm_activities", schema=None) as batch_op:
        batch_op.create_index("ix_activity_field_scheduled", ["field_id", "scheduled_date"], unique=False)
        batch_op.create_index(batch_op.f("ix_farm_activities_field_id"), ["field_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_farm_activities_workflow_run_id"), ["workflow_run_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("farm_activities", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_farm_activities_workflow_run_id"))
        batch_op.drop_index(batch_op.f("ix_farm_activities_field_id"))
        batch_op.drop_index("ix_activity_field_scheduled")

    op.drop_table("farm_activities")
    with op.batch_alter_table("suitability_assessments", schema=None) as batch_op:
        batch_op.drop_index("ix_suitability_field_created")
        batch_op.drop_index(batch_op.f("ix_suitability_assessments_workflow_run_id"))
        batch_op.drop_index(batch_op.f("ix_suitability_assessments_field_id"))

    op.drop_table("suitability_assessments")
    op.drop_table("soil_interpretations")
    with op.batch_alter_table("risk_findings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_risk_findings_workflow_run_id"))
        batch_op.drop_index(batch_op.f("ix_risk_findings_field_id"))
        batch_op.drop_index("ix_risk_field_created")

    op.drop_table("risk_findings")
    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_reports_workflow_run_id"))
        batch_op.drop_index(batch_op.f("ix_reports_field_id"))
        batch_op.drop_index(batch_op.f("ix_reports_farm_id"))

    op.drop_table("reports")
    with op.batch_alter_table("ml_predictions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ml_predictions_workflow_run_id"))
        batch_op.drop_index(batch_op.f("ix_ml_predictions_field_id"))
        batch_op.drop_index("ix_ml_field_created")

    op.drop_table("ml_predictions")
    with op.batch_alter_table("irrigation_assessments", schema=None) as batch_op:
        batch_op.drop_index("ix_irrigation_field_created")
        batch_op.drop_index(batch_op.f("ix_irrigation_assessments_workflow_run_id"))
        batch_op.drop_index(batch_op.f("ix_irrigation_assessments_field_id"))

    op.drop_table("irrigation_assessments")
    with op.batch_alter_table("approval_requests", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_approval_requests_workflow_run_id"))
        batch_op.drop_index(batch_op.f("ix_approval_requests_field_id"))
        batch_op.drop_index("ix_approval_field_status")

    op.drop_table("approval_requests")
    with op.batch_alter_table("agent_traces", schema=None) as batch_op:
        batch_op.drop_index("ix_agent_trace_run_sequence")

    op.drop_table("agent_traces")
    with op.batch_alter_table("workflow_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_workflow_runs_field_id"))
        batch_op.drop_index(batch_op.f("ix_workflow_runs_farm_id"))
        batch_op.drop_index("ix_workflow_field_created")

    op.drop_table("workflow_runs")
    with op.batch_alter_table("weather_snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_weather_snapshots_field_id"))
        batch_op.drop_index(batch_op.f("ix_weather_snapshots_farm_id"))
        batch_op.drop_index("ix_weather_snapshot_field_date")

    op.drop_table("weather_snapshots")
    with op.batch_alter_table("water_balance_records", schema=None) as batch_op:
        batch_op.drop_index("ix_water_field_applied")
        batch_op.drop_index(batch_op.f("ix_water_balance_records_field_id"))

    op.drop_table("water_balance_records")
    with op.batch_alter_table("soil_observations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_soil_observations_field_id"))
        batch_op.drop_index("ix_soil_observation_field_observed")

    op.drop_table("soil_observations")
    with op.batch_alter_table("sensor_readings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sensor_readings_field_id"))
        batch_op.drop_index("ix_sensor_reading_field_time")

    op.drop_table("sensor_readings")
    with op.batch_alter_table("alerts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_alerts_field_id"))
        batch_op.drop_index(batch_op.f("ix_alerts_farm_id"))
        batch_op.drop_index("ix_alert_field_fingerprint_status")

    op.drop_table("alerts")
    with op.batch_alter_table("fields", schema=None) as batch_op:
        batch_op.drop_index("ix_fields_farm_id_code")
        batch_op.drop_index(batch_op.f("ix_fields_farm_id"))

    op.drop_table("fields")
    with op.batch_alter_table("reference_documents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_reference_documents_category"))

    op.drop_table("reference_documents")
    with op.batch_alter_table("farms", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_farms_name"))

    op.drop_table("farms")
    # ### end Alembic commands ###
