import {
  BookOpen,
  CloudSun,
  Cpu,
  Eye,
  FlaskConical,
  Ruler,
  Scale,
  Sparkles,
  SquareStack,
  User,
  type LucideIcon,
} from 'lucide-react';
import { EVIDENCE_KINDS, type EvidenceKind } from '../../api/types';
import { Badge, type BadgeTone } from './Badge';
import { humaniseToken } from '../../lib/format';

/**
 * Provenance tags, mirroring the backend's `SourceKind` enum.
 * Every kind gets its own label, icon and colour so a reader can tell at a
 * glance whether a number was measured, forecast, retrieved or inferred.
 */
export interface EvidenceKindMeta {
  kind: EvidenceKind | string;
  label: string;
  description: string;
  tone: BadgeTone;
  Icon: LucideIcon;
}

export const EVIDENCE_KIND_META: Record<EvidenceKind, EvidenceKindMeta> = {
  measured: {
    kind: 'measured',
    label: 'Measured',
    description: 'A value read from a physical measurement (laboratory test or in-field probe).',
    tone: 'brand',
    Icon: Ruler,
  },
  observed: {
    kind: 'observed',
    label: 'Observed',
    description: 'A value derived from a time series of readings.',
    tone: 'info',
    Icon: Eye,
  },
  forecast: {
    kind: 'forecast',
    label: 'Forecast',
    description: 'A predicted value retrieved from a weather provider.',
    tone: 'violet',
    Icon: CloudSun,
  },
  retrieved_reference: {
    kind: 'retrieved_reference',
    label: 'Reference',
    description: 'Retrieved agronomic reference material (RAG citation).',
    tone: 'slate',
    Icon: BookOpen,
  },
  rule: {
    kind: 'rule',
    label: 'Rule',
    description: 'Produced by a deterministic agronomic rule.',
    tone: 'neutral',
    Icon: Scale,
  },
  ml_prediction: {
    kind: 'ml_prediction',
    label: 'ML prediction',
    description: 'Produced by a trained machine-learning model.',
    tone: 'warning',
    Icon: Cpu,
  },
  llm_narrative: {
    kind: 'llm_narrative',
    label: 'LLM narrative',
    description: 'Narrative text composed by a language model.',
    tone: 'violet',
    Icon: Sparkles,
  },
  deterministic_narrative: {
    kind: 'deterministic_narrative',
    label: 'Rule narrative',
    description: 'Narrative text composed deterministically from computed evidence.',
    tone: 'neutral',
    Icon: SquareStack,
  },
  user_input: {
    kind: 'user_input',
    label: 'User input',
    description: 'Supplied by a person through this application.',
    tone: 'brand',
    Icon: User,
  },
  simulated: {
    kind: 'simulated',
    label: 'Simulated',
    description: 'Generated by a simulator. This is not a physical measurement.',
    tone: 'warning',
    Icon: FlaskConical,
  },
};

const FALLBACK_META: EvidenceKindMeta = {
  kind: 'unknown',
  label: 'Unlabelled',
  description: 'Evidence with no recognised provenance tag.',
  tone: 'neutral',
  Icon: Eye,
};

export const isEvidenceKind = (value: unknown): value is EvidenceKind =>
  typeof value === 'string' && (EVIDENCE_KINDS as readonly string[]).includes(value);

export function evidenceKindMeta(kind: string | null | undefined): EvidenceKindMeta {
  if (isEvidenceKind(kind)) return EVIDENCE_KIND_META[kind];
  if (!kind) return FALLBACK_META;
  return {
    ...FALLBACK_META,
    kind,
    label: humaniseToken(kind, 'Unlabelled'),
    description: `Provenance tag "${kind}" is not part of the documented SourceKind enum.`,
  };
}

export interface EvidenceKindBadgeProps {
  kind: string;
  className?: string;
  /** Append the raw enum value, e.g. `retrieved_reference`. */
  showRaw?: boolean;
}

/**
 * Renders a provenance tag. Every value in `SourceKind` is supported; an
 * unrecognised value degrades to a neutral badge rather than rendering blank.
 */
export function EvidenceKindBadge({ kind, className, showRaw = false }: EvidenceKindBadgeProps) {
  const meta = evidenceKindMeta(kind);
  const { Icon } = meta;
  return (
    <Badge tone={meta.tone} title={`${meta.description} (kind: ${kind})`} className={className}>
      <Icon className="h-3 w-3" aria-hidden="true" />
      {meta.label}
      {showRaw ? <span className="font-mono opacity-70">({kind})</span> : null}
    </Badge>
  );
}

export default EvidenceKindBadge;